import {
  HTTP_BASE_URL_INTERCEPTOR,
  HTTP_ENTITY_PAGINATION_INTERCEPTOR,
  HTTP_ERROR_INTERCEPTOR,
  HTTP_RESPONSE_UNWRAP_INTERCEPTOR,
} from './interceptors';

export const HTTP_CORE_INTERCEPTORS = [
  HTTP_BASE_URL_INTERCEPTOR,
  HTTP_ERROR_INTERCEPTOR,
  HTTP_ENTITY_PAGINATION_INTERCEPTOR,
  HTTP_RESPONSE_UNWRAP_INTERCEPTOR,
] as const;
